identifier:
  image: semtech/mu-identifier:1.0.0
  ports:
    - "80:80"
  links:
    - dispatcher:dispatcher
dispatcher:
  image: semtech/mu-dispatcher:1.0.1
  volumes:
    - ./config/dispatcher:/config
  links:
    - resource:resource
database:
  image: tenforce/virtuoso:virtuoso-v7.2.0-latest
  environment:
    SPARQL_UPDATE: "true"
    DEFAULT_GRAPH: http://mu.semte.ch/application
    DBA_PASSWORD: dba
  ports:
    - "8890:8890"
  volumes:
    - ./data/db:/var/lib/virtuoso/db
resource:
  image: semtech/mu-cl-resources:1.8.1
  volumes:
    - ./config/resources:/config
  environment:
    BOOT: mu-cl-resources
  links:
    - database:database
  ports:
    - 8080:80